import type { Config } from "tailwindcss";
import fontFamily from "tailwindcss/defaultTheme";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {

      fontFamily: {
        // Existing fonts
        sans: ["Inter", ...fontFamily.fontFamily.sans],
        serif: ["Merriweather", ...fontFamily.fontFamily.serif],
        mono: ["Roboto Mono", ...fontFamily.fontFamily.mono],
        display: ["Playfair Display", ...fontFamily.fontFamily.serif],
        handwriting: ["Caveat", ...fontFamily.fontFamily.sans],
        futuristic: ["Orbitron", ...fontFamily.fontFamily.sans],
        retro: ["VT323", ...fontFamily.fontFamily.mono],
        elegant: ["Cormorant Garamond", ...fontFamily.fontFamily.serif],
        quirky: ["Fredoka One", ...fontFamily.fontFamily.sans],
        geometric: ["Montserrat", ...fontFamily.fontFamily.sans],
        
        // Your new custom fonts
        fenix: ["Fenix", ...fontFamily.fontFamily.serif],
        butcherman: ["Butcherman", ...fontFamily.fontFamily.serif],
        fruktur: ["Fruktur", ...fontFamily.fontFamily.serif],

        // Custom fonts from public/fonts
        "custom-alexbrush-regular": ["AlexBrush", ...fontFamily.fontFamily.serif],
        "custom-allertastencil-regular": ["AllertaStencil", ...fontFamily.fontFamily.sans],
        "custom-allison-regular": ["Allison", ...fontFamily.fontFamily.serif],
        "custom-allura-regular": ["Allura", ...fontFamily.fontFamily.serif],
        "custom-alumnisans-variablefont-wght": ["Alumni Sans", ...fontFamily.fontFamily.sans],
        "custom-berkshireswash-regular": ["Berkshire Swash", ...fontFamily.fontFamily.serif],
        "custom-bitcountpropsingle-variablefont-crsv-elsh-elxp-slnt-wght": ["Bitcount Prop Single", ...fontFamily.fontFamily.mono],
        "custom-bitcountpropsingle-cursive-regular": ["Bitcount Prop Single", ...fontFamily.fontFamily.mono],
        "custom-bodonimoda-variablefont-opsz-wght": ["Bodoni Moda", ...fontFamily.fontFamily.serif],
        "custom-bungeeinline-regular": ["Bungee Inline", ...fontFamily.fontFamily.sans],
        "custom-bungeetint-regular": ["Bungee Tint", ...fontFamily.fontFamily.sans],
        "custom-caesardressing-regular": ["Caesar Dressing", ...fontFamily.fontFamily.sans],
        "custom-caveat-variablefont-wght": ["Caveat", ...fontFamily.fontFamily.sans],
        "custom-cinzel-variablefont-wght": ["Cinzel", ...fontFamily.fontFamily.serif],
        "custom-courgette-regular": ["Courgette", ...fontFamily.fontFamily.serif],
        "custom-creepster-regular": ["Creepster", ...fontFamily.fontFamily.sans],
        "custom-damion-regular": ["Damion", ...fontFamily.fontFamily.serif],
        "custom-dancingscript-variablefont-wght": ["Dancing Script", ...fontFamily.fontFamily.serif],
        "custom-eduqldhand-variablefont-wght": ["Edu QLD Hand", ...fontFamily.fontFamily.serif],
        "custom-eduvicwanthand-variablefont-wght": ["Edu VIC WA NT Hand", ...fontFamily.fontFamily.serif],
        "custom-exile-regular": ["Exile", ...fontFamily.fontFamily.sans],
        "custom-exo-variablefont-wght": ["Exo", ...fontFamily.fontFamily.sans],
        "custom-frederickathegreat-regular": ["Fredericka the Great", ...fontFamily.fontFamily.serif],
        "custom-gloriahallelujah-regular": ["Gloria Hallelujah", ...fontFamily.fontFamily.serif],
        "custom-goldman-bold": ["Goldman", ...fontFamily.fontFamily.sans],
        "custom-goldman-regular": ["Goldman", ...fontFamily.fontFamily.sans],
        "custom-gravitasone-regular": ["Gravitas One", ...fontFamily.fontFamily.sans],
        "custom-greatvibes-regular": ["Great Vibes", ...fontFamily.fontFamily.serif],
        "custom-homemadeapple-regular": ["Homemade Apple", ...fontFamily.fontFamily.serif],
        "custom-indieflower-regular": ["Indie Flower", ...fontFamily.fontFamily.serif],
        "custom-justanotherhand-regular": ["Just Another Hand", ...fontFamily.fontFamily.serif],
        "custom-lato-regular": ["Lato", ...fontFamily.fontFamily.sans],
        "custom-lato-thin": ["Lato", ...fontFamily.fontFamily.sans],
        "custom-leckerlione-regular": ["Leckerli One", ...fontFamily.fontFamily.serif],
        "custom-libertinusmono-regular": ["Libertinus Mono", ...fontFamily.fontFamily.mono],
        "custom-lobstertwo-regular": ["Lobster Two", ...fontFamily.fontFamily.serif],
        "custom-manufacturingconsent-regular": ["Manufacturing Consent", ...fontFamily.fontFamily.sans],
        "custom-marcellus-regular": ["Marcellus", ...fontFamily.fontFamily.serif],
        "custom-marckscript-regular": ["Marck Script", ...fontFamily.fontFamily.serif],
        "custom-michroma-regular": ["Michroma", ...fontFamily.fontFamily.sans],
        "custom-monoton-regular": ["Monoton", ...fontFamily.fontFamily.sans],
        "custom-montserrat-italic-variablefont-wght": ["Montserrat", ...fontFamily.fontFamily.sans],
        "custom-mrdafoe-regular": ["Mr Dafoe", ...fontFamily.fontFamily.serif],
        "custom-mrssaintdelafield-regular": ["Mrs Saint Delafield", ...fontFamily.fontFamily.serif],
        "custom-mysoul-regular": ["My Soul", ...fontFamily.fontFamily.serif],
        "custom-nothingyoucoulddo-regular": ["Nothing You Could Do", ...fontFamily.fontFamily.serif],
        "custom-orbitron-variablefont-wght": ["Orbitron", ...fontFamily.fontFamily.sans],
        "custom-pacifico-regular": ["Pacifico", ...fontFamily.fontFamily.serif],
        "custom-parisienne-regular": ["Parisienne", ...fontFamily.fontFamily.serif],
        "custom-permanentmarker-regular": ["Permanent Marker", ...fontFamily.fontFamily.serif],
        "custom-pinyonscript-regular": ["Pinyon Script", ...fontFamily.fontFamily.serif],
        "custom-protestrevolution-regular": ["Protest Revolution", ...fontFamily.fontFamily.sans],
        "custom-reeniebeanie-regular": ["Reenie Beanie", ...fontFamily.fontFamily.serif],
        "custom-robotocondensed-italic-variablefont-wght": ["Roboto Condensed", ...fontFamily.fontFamily.sans],
        "custom-robotocondensed-variablefont-wght": ["Roboto Condensed", ...fontFamily.fontFamily.sans],
        "custom-rocksalt-regular": ["Rock Salt", ...fontFamily.fontFamily.serif],
        "custom-rubikmonoone-regular": ["Rubik Mono One", ...fontFamily.fontFamily.mono],
        "custom-rubikmoonrocks-regular": ["Rubik Moonrocks", ...fontFamily.fontFamily.sans],
        "custom-rye-regular": ["Rye", ...fontFamily.fontFamily.serif],
        "custom-sacramento-regular": ["Sacramento", ...fontFamily.fontFamily.serif],
        "custom-satisfy-regular": ["Satisfy", ...fontFamily.fontFamily.serif],
        "custom-savate-variablefont-wght": ["Savate", ...fontFamily.fontFamily.sans],
        "custom-shadowsintolight-regular": ["Shadows Into Light", ...fontFamily.fontFamily.serif],
        "custom-smoochsans-variablefont-wght": ["Smooch Sans", ...fontFamily.fontFamily.sans],
        "custom-sourceserif4-variablefont-opsz-wght": ["Source Serif 4", ...fontFamily.fontFamily.serif],
        "custom-specialgothicexpandedone-regular": ["Special Gothic Expanded One", ...fontFamily.fontFamily.sans],
        "custom-squadaone-regular": ["Squada One", ...fontFamily.fontFamily.sans],
        "custom-tangerine-bold": ["Tangerine", ...fontFamily.fontFamily.serif],
        "custom-titilliumweb-extralightitalic": ["Titillium Web", ...fontFamily.fontFamily.sans],
        "custom-titilliumweb-regular": ["Titillium Web", ...fontFamily.fontFamily.sans],
        "custom-winkyrough-variablefont-wght": ["Winky Rough", ...fontFamily.fontFamily.serif],
        "custom-zeyada-regular": ["Zeyada", ...fontFamily.fontFamily.serif],
        "custom-zillaslab-medium": ["Zilla Slab", ...fontFamily.fontFamily.serif],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;