import { LocalSound } from "../types";

export const localSounds: LocalSound[] = [
  {
    id: "local-1",
    title: "Take Care Of Yourself Full Version",
    artist: "Local",
    duration: 154,
    file: "/sounds/01_Take_Care_of_Yourself_full_version.mp3",
  },
  {
    id: "local-2",
    title: "Upbeat Corporate",
    artist: "Local",
    duration: 146,
    file: "/sounds/138_upbeat_corporate.mp3",
  },
  {
    id: "local-3",
    title: "Food Full",
    artist: "Local",
    duration: 132,
    file: "/sounds/1_Food_Full.wav",
  },
  {
    id: "local-4",
    title: "Commercial Full Version",
    artist: "Local",
    duration: 132,
    file: "/sounds/2_Commercial_Full_Version.wav",
  },
  {
    id: "local-5",
    title: "Happy",
    artist: "Local",
    duration: 132,
    file: "/sounds/331_Happy.mp3",
  },
  {
    id: "local-6",
    title: "Inspiring Corporate",
    artist: "Local",
    duration: 162,
    file: "/sounds/331_Inspiring_Corporate.mp3",
  },
  {
    id: "local-7",
    title: "Uplifting Corporate Upbeat Motivational",
    artist: "Local",
    duration: 138,
    file: "/sounds/331_Uplifting_Corporate_Upbeat_Motivational.mp3",
  },
  {
    id: "local-8",
    title: "S Fashion Week",
    artist: "Local",
    duration: 112,
    file: "/sounds/80s_Fashion_Week.mp3",
  },
  {
    id: "local-9",
    title: "A Beach Version 1",
    artist: "Local",
    duration: 154,
    file: "/sounds/A_Beach_version_1.mp3",
  },
  {
    id: "local-10",
    title: "A Corporate",
    artist: "Local",
    duration: 136,
    file: "/sounds/A_Corporate.wav",
  },
  {
    id: "local-11",
    title: "A Medical",
    artist: "Local",
    duration: 164,
    file: "/sounds/A_Medical.mp3",
  },
  {
    id: "local-12",
    title: "A Motivational Corporate Full Version",
    artist: "Local",
    duration: 170,
    file: "/sounds/A_Motivational_Corporate_full_version.mp3",
  },
  {
    id: "local-13",
    title: "A Travel",
    artist: "Local",
    duration: 137,
    file: "/sounds/A_Travel.mp3",
  },
  {
    id: "local-14",
    title: "Above And Beyond",
    artist: "Local",
    duration: 158,
    file: "/sounds/Above_And_Beyond.wav",
  },
  {
    id: "local-15",
    title: "Advert",
    artist: "Local",
    duration: 149,
    file: "/sounds/Advert.mp3",
  },
  {
    id: "local-16",
    title: "Advertisement By Musicstock",
    artist: "Local",
    duration: 145,
    file: "/sounds/Advertisement_by_MusicStock.mp3",
  },
  {
    id: "local-17",
    title: "Alex Under The Sky Cinematic Movie",
    artist: "Local",
    duration: 128,
    file: "/sounds/Alex_Under_The_Sky_Cinematic_Movie.mp3",
  },
  {
    id: "local-18",
    title: "Ambient Music",
    artist: "Local",
    duration: 134,
    file: "/sounds/Ambient_Music.mp3",
  },
  {
    id: "local-19",
    title: "An Education",
    artist: "Local",
    duration: 134,
    file: "/sounds/An_Education.wav",
  },
  {
    id: "local-20",
    title: "Auburn Hair",
    artist: "Local",
    duration: 179,
    file: "/sounds/Auburn_Hair.mp3",
  },
  {
    id: "local-21",
    title: "Audiocopper Technology Ambient Presentation Full Version",
    artist: "Local",
    duration: 159,
    file: "/sounds/AudioCopper_Technology_Ambient_Presentation_Full_Version.wav",
  },
  {
    id: "local-22",
    title: "Be Travel",
    artist: "Local",
    duration: 140,
    file: "/sounds/Be_Travel.wav",
  },
  {
    id: "local-23",
    title: "Beautiful",
    artist: "Local",
    duration: 143,
    file: "/sounds/Beautiful.mp3",
  },
  {
    id: "local-24",
    title: "Business",
    artist: "Local",
    duration: 145,
    file: "/sounds/Business.mp3",
  },
  {
    id: "local-25",
    title: "Business",
    artist: "Local",
    duration: 136,
    file: "/sounds/Business.wav",
  },
  {
    id: "local-26",
    title: "Business Background",
    artist: "Local",
    duration: 156,
    file: "/sounds/Business_Background.wav",
  },
  {
    id: "local-27",
    title: "Care",
    artist: "Local",
    duration: 146,
    file: "/sounds/Care.mp3",
  },
  {
    id: "local-28",
    title: "Caring For Others",
    artist: "Local",
    duration: 176,
    file: "/sounds/Caring_for_Others.mp3",
  },
  {
    id: "local-29",
    title: "Casual Acoustic Stroll",
    artist: "Local",
    duration: 131,
    file: "/sounds/Casual_Acoustic_Stroll.mp3",
  },
  {
    id: "local-30",
    title: "Choose To See",
    artist: "Local",
    duration: 154,
    file: "/sounds/Choose_to_See.mp3",
  },
  {
    id: "local-31",
    title: "Comfort",
    artist: "Local",
    duration: 122,
    file: "/sounds/Comfort.wav",
  },
  {
    id: "local-32",
    title: "Community Main",
    artist: "Local",
    duration: 153,
    file: "/sounds/Community_main.mp3",
  },
  {
    id: "local-33",
    title: "Corporate",
    artist: "Local",
    duration: 159,
    file: "/sounds/Corporate.mp3",
  },
  {
    id: "local-34",
    title: "Corporate Ambient",
    artist: "Local",
    duration: 146,
    file: "/sounds/Corporate_Ambient.mp3",
  },
  {
    id: "local-35",
    title: "Corporate History",
    artist: "Local",
    duration: 169,
    file: "/sounds/Corporate_History.mp3",
  },
  {
    id: "local-36",
    title: "Corporate Medical Full",
    artist: "Local",
    duration: 156,
    file: "/sounds/Corporate_Medical_Full.mp3",
  },
  {
    id: "local-37",
    title: "Corporate Motivational Pop",
    artist: "Local",
    duration: 136,
    file: "/sounds/Corporate_Motivational_Pop.mp3",
  },
  {
    id: "local-38",
    title: "Corporate Technology",
    artist: "Local",
    duration: 150,
    file: "/sounds/Corporate_Technology.mp3",
  },
  {
    id: "local-39",
    title: "Corporate Upbeat",
    artist: "Local",
    duration: 150,
    file: "/sounds/Corporate_Upbeat.mp3",
  },
  {
    id: "local-40",
    title: "Dance",
    artist: "Local",
    duration: 137,
    file: "/sounds/Dance.mp3",
  },
  {
    id: "local-41",
    title: "Design Trends Full Version",
    artist: "Local",
    duration: 150,
    file: "/sounds/Design_Trends_Full_Version.mp3",
  },
  {
    id: "local-42",
    title: "Diamond",
    artist: "Local",
    duration: 142,
    file: "/sounds/Diamond.mp3",
  },
  {
    id: "local-43",
    title: "Dream Your Dreams",
    artist: "Local",
    duration: 135,
    file: "/sounds/Dream_Your_Dreams.mp3",
  },
  {
    id: "local-44",
    title: "Easy",
    artist: "Local",
    duration: 136,
    file: "/sounds/Easy.wav",
  },
  {
    id: "local-45",
    title: "Education",
    artist: "Local",
    duration: 142,
    file: "/sounds/Education.wav",
  },
  {
    id: "local-46",
    title: "Education Main",
    artist: "Local",
    duration: 202,
    file: "/sounds/Education_main.mp3",
  },
  {
    id: "local-47",
    title: "Energetic Upbeat Action Sports",
    artist: "Local",
    duration: 133,
    file: "/sounds/Energetic_Upbeat_Action_Sports.mp3",
  },
  {
    id: "local-48",
    title: "Every Day",
    artist: "Local",
    duration: 142,
    file: "/sounds/Every_Day.wav",
  },
  {
    id: "local-49",
    title: "Exciting",
    artist: "Local",
    duration: 134,
    file: "/sounds/Exciting.mp3",
  },
  {
    id: "local-50",
    title: "Fashion Background",
    artist: "Local",
    duration: 152,
    file: "/sounds/Fashion_Background.mp3",
  },
  {
    id: "local-51",
    title: "Fashion Chill House Full",
    artist: "Local",
    duration: 130,
    file: "/sounds/Fashion_Chill_House_full.mp3",
  },
  {
    id: "local-52",
    title: "Fashion On",
    artist: "Local",
    duration: 130,
    file: "/sounds/Fashion_On.wav",
  },
  {
    id: "local-53",
    title: "Fashion Trend",
    artist: "Local",
    duration: 138,
    file: "/sounds/Fashion_Trend.mp3",
  },
  {
    id: "local-54",
    title: "Fashionable",
    artist: "Local",
    duration: 118,
    file: "/sounds/Fashionable.mp3",
  },
  {
    id: "local-55",
    title: "File A 210 Greenrocketaudio Upbeat Corporate Full Version",
    artist: "Local",
    duration: 130,
    file: "/sounds/File_A_210_GreenRocketAudio_Upbeat_Corporate_Full_Version.mp3",
  },
  {
    id: "local-56",
    title: "File A 217 331 Corporate Background Music Full Version",
    artist: "Local",
    duration: 137,
    file: "/sounds/File_A_217_331_Corporate_Background_Music_Full_Version.mp3",
  },
  {
    id: "local-57",
    title: "File A 219 Bearstockmusic This Ambient Music Full",
    artist: "Local",
    duration: 139,
    file: "/sounds/File_A_219_BearStockMusic_This_Ambient_Music_Full.mp3",
  },
  {
    id: "local-58",
    title: "File A 316 331 Aspire Full",
    artist: "Local",
    duration: 197,
    file: "/sounds/File_A_316_331_Aspire_full.mp3",
  },
  {
    id: "local-59",
    title: "Finaldestination",
    artist: "Local",
    duration: 144,
    file: "/sounds/FinalDestination.mp3",
  },
  {
    id: "local-60",
    title: "Finance And Bank",
    artist: "Local",
    duration: 159,
    file: "/sounds/Finance_and_Bank.mp3",
  },
  {
    id: "local-61",
    title: "Fitness",
    artist: "Local",
    duration: 135,
    file: "/sounds/Fitness.mp3",
  },
  {
    id: "local-62",
    title: "Flight",
    artist: "Local",
    duration: 119,
    file: "/sounds/Flight.mp3",
  },
  {
    id: "local-63",
    title: "Food",
    artist: "Local",
    duration: 125,
    file: "/sounds/Food.wav",
  },
  {
    id: "local-64",
    title: "Food Full 154",
    artist: "Local",
    duration: 125,
    file: "/sounds/Food_full_154.mp3",
  },
  {
    id: "local-65",
    title: "For Electronic",
    artist: "Local",
    duration: 143,
    file: "/sounds/For_Electronic.mp3",
  },
  {
    id: "local-66",
    title: "For Food Full 165",
    artist: "Local",
    duration: 124,
    file: "/sounds/For_Food_full_165.mp3",
  },
  {
    id: "local-67",
    title: "For Travel",
    artist: "Local",
    duration: 155,
    file: "/sounds/For_Travel.mp3",
  },
  {
    id: "local-68",
    title: "Four Seasons Version 1",
    artist: "Local",
    duration: 143,
    file: "/sounds/Four_Seasons_Version_1.mp3",
  },
  {
    id: "local-69",
    title: "Fresh",
    artist: "Local",
    duration: 207,
    file: "/sounds/Fresh.wav",
  },
  {
    id: "local-70",
    title: "Friendly",
    artist: "Local",
    duration: 140,
    file: "/sounds/Friendly.wav",
  },
  {
    id: "local-71",
    title: "Full Track",
    artist: "Local",
    duration: 139,
    file: "/sounds/Full_Track.mp3",
  },
  {
    id: "local-72",
    title: "Gift",
    artist: "Local",
    duration: 144,
    file: "/sounds/Gift.mp3",
  },
  {
    id: "local-73",
    title: "Going For Gold",
    artist: "Local",
    duration: 168,
    file: "/sounds/Going_for_Gold.mp3",
  },
  {
    id: "local-74",
    title: "Growth",
    artist: "Local",
    duration: 146,
    file: "/sounds/Growth.mp3",
  },
  {
    id: "local-75",
    title: "Guitar Corporate",
    artist: "Local",
    duration: 155,
    file: "/sounds/Guitar_Corporate.mp3",
  },
  {
    id: "local-76",
    title: "Happiness Full",
    artist: "Local",
    duration: 130,
    file: "/sounds/Happiness_Full.mp3",
  },
  {
    id: "local-77",
    title: "Happy Friend",
    artist: "Local",
    duration: 123,
    file: "/sounds/Happy_Friend.wav",
  },
  {
    id: "local-78",
    title: "Happy And Cheerful",
    artist: "Local",
    duration: 146,
    file: "/sounds/Happy_and_Cheerful.mp3",
  },
  {
    id: "local-79",
    title: "Health",
    artist: "Local",
    duration: 140,
    file: "/sounds/Health.wav",
  },
  {
    id: "local-80",
    title: "Home",
    artist: "Local",
    duration: 155,
    file: "/sounds/Home.mp3",
  },
  {
    id: "local-81",
    title: "Ice Cream",
    artist: "Local",
    duration: 210,
    file: "/sounds/Ice_cream.mp3",
  },
  {
    id: "local-82",
    title: "Inspirational Colorsl Main Track",
    artist: "Local",
    duration: 146,
    file: "/sounds/Inspirational_Colorsl_Main_Track.mp3",
  },
  {
    id: "local-83",
    title: "Inspire",
    artist: "Local",
    duration: 148,
    file: "/sounds/Inspire.mp3",
  },
  {
    id: "local-84",
    title: "Inspiring Background",
    artist: "Local",
    duration: 161,
    file: "/sounds/Inspiring_Background.mp3",
  },
  {
    id: "local-85",
    title: "Inspiring Corporate Background",
    artist: "Local",
    duration: 136,
    file: "/sounds/Inspiring_Corporate_Background.mp3",
  },
  {
    id: "local-86",
    title: "Inspiring Muted Guitar",
    artist: "Local",
    duration: 133,
    file: "/sounds/Inspiring_Muted_Guitar.mp3",
  },
  {
    id: "local-87",
    title: "Inspiring Website Presentation",
    artist: "Local",
    duration: 153,
    file: "/sounds/Inspiring_Website_Presentation.mp3",
  },
  {
    id: "local-88",
    title: "Inspiring Wedding Guitar",
    artist: "Local",
    duration: 190,
    file: "/sounds/Inspiring_Wedding_Guitar.mp3",
  },
  {
    id: "local-89",
    title: "Institute",
    artist: "Local",
    duration: 145,
    file: "/sounds/Institute.wav",
  },
  {
    id: "local-90",
    title: "Interest",
    artist: "Local",
    duration: 154,
    file: "/sounds/Interest.mp3",
  },
  {
    id: "local-91",
    title: "Investment",
    artist: "Local",
    duration: 144,
    file: "/sounds/Investment.mp3",
  },
  {
    id: "local-92",
    title: "It Is Business",
    artist: "Local",
    duration: 147,
    file: "/sounds/It_Is_Business.mp3",
  },
  {
    id: "local-93",
    title: "Kids Playing",
    artist: "Local",
    duration: 144,
    file: "/sounds/Kids_Playing.mp3",
  },
  {
    id: "local-94",
    title: "Kitchen",
    artist: "Local",
    duration: 128,
    file: "/sounds/Kitchen.mp3",
  },
  {
    id: "local-95",
    title: "Lawyer 1",
    artist: "Local",
    duration: 157,
    file: "/sounds/Lawyer_1.wav",
  },
  {
    id: "local-96",
    title: "Learning 01",
    artist: "Local",
    duration: 144,
    file: "/sounds/Learning_01.mp3",
  },
  {
    id: "local-97",
    title: "Learning Corporate Background",
    artist: "Local",
    duration: 147,
    file: "/sounds/Learning_Corporate_Background.mp3",
  },
  {
    id: "local-98",
    title: "Learning Intro By Musicstock",
    artist: "Local",
    duration: 42,
    file: "/sounds/Learning_Intro_by_MusicStock.mp3",
  },
  {
    id: "local-99",
    title: "Lifestyle",
    artist: "Local",
    duration: 131,
    file: "/sounds/Lifestyle.mp3",
  },
  {
    id: "local-100",
    title: "Light In Her Hair",
    artist: "Local",
    duration: 179,
    file: "/sounds/Light_In_Her_Hair.mp3",
  },
  {
    id: "local-101",
    title: "Light Sound Fashion",
    artist: "Local",
    duration: 118,
    file: "/sounds/Light_Sound_Fashion.mp3",
  },
  {
    id: "local-102",
    title: "Light Sound Fashion Lounge House",
    artist: "Local",
    duration: 139,
    file: "/sounds/Light_Sound_Fashion_Lounge_House.mp3",
  },
  {
    id: "local-103",
    title: "Light Sound Fashionable",
    artist: "Local",
    duration: 122,
    file: "/sounds/Light_Sound_Fashionable.mp3",
  },
  {
    id: "local-104",
    title: "Light Sound Happy Animation",
    artist: "Local",
    duration: 131,
    file: "/sounds/Light_Sound_Happy_Animation.mp3",
  },
  {
    id: "local-105",
    title: "Light Sound House",
    artist: "Local",
    duration: 134,
    file: "/sounds/Light_Sound_House.mp3",
  },
  {
    id: "local-106",
    title: "Light Sound Kitchen",
    artist: "Local",
    duration: 127,
    file: "/sounds/Light_Sound_Kitchen.mp3",
  },
  {
    id: "local-107",
    title: "Light Sound The Fashion",
    artist: "Local",
    duration: 148,
    file: "/sounds/Light_Sound_The_Fashion.mp3",
  },
  {
    id: "local-108",
    title: "Love [version 1]",
    artist: "Local",
    duration: 124,
    file: "/sounds/Love_[Version_1].wav",
  },
  {
    id: "local-109",
    title: "Marian In Style",
    artist: "Local",
    duration: 152,
    file: "/sounds/MARiAN_In_Style.mp3",
  },
  {
    id: "local-110",
    title: "Mgm Corporate Trend",
    artist: "Local",
    duration: 148,
    file: "/sounds/MGM_Corporate_Trend.mp3",
  },
  {
    id: "local-111",
    title: "Mgm Your Body",
    artist: "Local",
    duration: 146,
    file: "/sounds/MGM_Your_Body.mp3",
  },
  {
    id: "local-112",
    title: "Main Version",
    artist: "Local",
    duration: 139,
    file: "/sounds/Main_Version.mp3",
  },
  {
    id: "local-113",
    title: "Makeup Tutorial",
    artist: "Local",
    duration: 127,
    file: "/sounds/Makeup_Tutorial.wav",
  },
  {
    id: "local-114",
    title: "Medical",
    artist: "Local",
    duration: 132,
    file: "/sounds/Medical.wav",
  },
  {
    id: "local-115",
    title: "Medical Full",
    artist: "Local",
    duration: 145,
    file: "/sounds/Medical_Full.mp3",
  },
  {
    id: "local-116",
    title: "Melodic Corporate 2",
    artist: "Local",
    duration: 125,
    file: "/sounds/Melodic_Corporate_2.mp3",
  },
  {
    id: "local-117",
    title: "Modern Corporate Full Version",
    artist: "Local",
    duration: 143,
    file: "/sounds/Modern_Corporate_full_version.mp3",
  },
  {
    id: "local-118",
    title: "Morning Coffee",
    artist: "Local",
    duration: 142,
    file: "/sounds/Morning_Coffee.mp3",
  },
  {
    id: "local-119",
    title: "Motivate",
    artist: "Local",
    duration: 141,
    file: "/sounds/Motivate.mp3",
  },
  {
    id: "local-120",
    title: "Motivating",
    artist: "Local",
    duration: 146,
    file: "/sounds/Motivating.mp3",
  },
  {
    id: "local-121",
    title: "Motivation",
    artist: "Local",
    duration: 154,
    file: "/sounds/Motivation.mp3",
  },
  {
    id: "local-122",
    title: "Motivational",
    artist: "Local",
    duration: 152,
    file: "/sounds/Motivational.mp3",
  },
  {
    id: "local-123",
    title: "Motivational Corporate",
    artist: "Local",
    duration: 134,
    file: "/sounds/Motivational_Corporate.mp3",
  },
  {
    id: "local-124",
    title: "Music Corporate",
    artist: "Local",
    duration: 143,
    file: "/sounds/Music_Corporate.mp3",
  },
  {
    id: "local-125",
    title: "Nikin Elegant Travel Fashion Opener",
    artist: "Local",
    duration: 131,
    file: "/sounds/NikiN_Elegant_Travel_Fashion_Opener.mp3",
  },
  {
    id: "local-126",
    title: "Not A Care In The World",
    artist: "Local",
    duration: 144,
    file: "/sounds/Not_a_Care_in_the_World.mp3",
  },
  {
    id: "local-127",
    title: "Office",
    artist: "Local",
    duration: 129,
    file: "/sounds/Office.mp3",
  },
  {
    id: "local-128",
    title: "Office",
    artist: "Local",
    duration: 137,
    file: "/sounds/Office.wav",
  },
  {
    id: "local-129",
    title: "Online Marketing",
    artist: "Local",
    duration: 149,
    file: "/sounds/Online_Marketing.mp3",
  },
  {
    id: "local-130",
    title: "Organic Ambient Music Full Version",
    artist: "Local",
    duration: 143,
    file: "/sounds/Organic_Ambient_Music_Full_Version.mp3",
  },
  {
    id: "local-131",
    title: "Pop Energetic",
    artist: "Local",
    duration: 138,
    file: "/sounds/Pop_Energetic.wav",
  },
  {
    id: "local-132",
    title: "Pop Uplifting Energetic Summer House Full",
    artist: "Local",
    duration: 104,
    file: "/sounds/Pop_Uplifting_Energetic_Summer_House_Full.mp3",
  },
  {
    id: "local-133",
    title: "Positive",
    artist: "Local",
    duration: 188,
    file: "/sounds/Positive.mp3",
  },
  {
    id: "local-134",
    title: "Product",
    artist: "Local",
    duration: 150,
    file: "/sounds/Product.mp3",
  },
  {
    id: "local-135",
    title: "Professional",
    artist: "Local",
    duration: 144,
    file: "/sounds/Professional.wav",
  },
  {
    id: "local-136",
    title: "Real Estate",
    artist: "Local",
    duration: 149,
    file: "/sounds/Real_Estate.mp3",
  },
  {
    id: "local-137",
    title: "Relaxing",
    artist: "Local",
    duration: 118,
    file: "/sounds/Relaxing.mp3",
  },
  {
    id: "local-138",
    title: "Ringing Xmas",
    artist: "Local",
    duration: 131,
    file: "/sounds/Ringing_Xmas.mp3",
  },
  {
    id: "local-139",
    title: "Santas Bag",
    artist: "Local",
    duration: 148,
    file: "/sounds/Santas_Bag.mp3",
  },
  {
    id: "local-140",
    title: "Soft Background",
    artist: "Local",
    duration: 134,
    file: "/sounds/Soft_Background.mp3",
  },
  {
    id: "local-141",
    title: "Stereo Nuts Ambient Main",
    artist: "Local",
    duration: 163,
    file: "/sounds/Stereo_Nuts_Ambient_Main.mp3",
  },
  {
    id: "local-142",
    title: "Studiokolomna Main Track",
    artist: "Local",
    duration: 150,
    file: "/sounds/StudioKolomna_Main_Track.mp3",
  },
  {
    id: "local-143",
    title: "Study",
    artist: "Local",
    duration: 141,
    file: "/sounds/Study.wav",
  },
  {
    id: "local-144",
    title: "Style",
    artist: "Local",
    duration: 136,
    file: "/sounds/Style.mp3",
  },
  {
    id: "local-145",
    title: "Summer Corporate",
    artist: "Local",
    duration: 129,
    file: "/sounds/Summer_Corporate.mp3",
  },
  {
    id: "local-146",
    title: "Summer Season Opening",
    artist: "Local",
    duration: 123,
    file: "/sounds/Summer_Season_Opening.mp3",
  },
  {
    id: "local-147",
    title: "Summer Upbeat Sports Pop",
    artist: "Local",
    duration: 124,
    file: "/sounds/Summer_Upbeat_Sports_Pop.mp3",
  },
  {
    id: "local-148",
    title: "Summer Uplifting Dance Full",
    artist: "Local",
    duration: 90,
    file: "/sounds/Summer_Uplifting_Dance_Full.mp3",
  },
  {
    id: "local-149",
    title: "Sweet Memories 2000074 16bit",
    artist: "Local",
    duration: 128,
    file: "/sounds/Sweet_Memories_2000074_16bit.wav",
  },
  {
    id: "local-150",
    title: "Swim And Fun",
    artist: "Local",
    duration: 140,
    file: "/sounds/Swim_and_Fun.mp3",
  },
  {
    id: "local-151",
    title: "Teaching",
    artist: "Local",
    duration: 149,
    file: "/sounds/Teaching.mp3",
  },
  {
    id: "local-152",
    title: "Technical",
    artist: "Local",
    duration: 166,
    file: "/sounds/Technical.mp3",
  },
  {
    id: "local-153",
    title: "Technology",
    artist: "Local",
    duration: 134,
    file: "/sounds/Technology.mp3",
  },
  {
    id: "local-154",
    title: "Technology",
    artist: "Local",
    duration: 167,
    file: "/sounds/Technology.wav",
  },
  {
    id: "local-155",
    title: "Technology Development",
    artist: "Local",
    duration: 147,
    file: "/sounds/Technology_Development.mp3",
  },
  {
    id: "local-156",
    title: "The Corporate Background",
    artist: "Local",
    duration: 168,
    file: "/sounds/The_Corporate_Background.mp3",
  },
  {
    id: "local-157",
    title: "The Corporate Background 2",
    artist: "Local",
    duration: 104,
    file: "/sounds/The_Corporate_Background_2.mp3",
  },
  {
    id: "local-158",
    title: "The Fashionist No Vocal",
    artist: "Local",
    duration: 136,
    file: "/sounds/The_Fashionist_No_Vocal.wav",
  },
  {
    id: "local-159",
    title: "The Holiday",
    artist: "Local",
    duration: 157,
    file: "/sounds/The_Holiday.mp3",
  },
  {
    id: "local-160",
    title: "The House",
    artist: "Local",
    duration: 128,
    file: "/sounds/The_House.mp3",
  },
  {
    id: "local-161",
    title: "The Medical",
    artist: "Local",
    duration: 128,
    file: "/sounds/The_Medical.mp3",
  },
  {
    id: "local-162",
    title: "The Medical",
    artist: "Local",
    duration: 130,
    file: "/sounds/The_Medical.wav",
  },
  {
    id: "local-163",
    title: "The Presentation",
    artist: "Local",
    duration: 174,
    file: "/sounds/The_Presentation.wav",
  },
  {
    id: "local-164",
    title: "The Suit",
    artist: "Local",
    duration: 159,
    file: "/sounds/The_Suit.mp3",
  },
  {
    id: "local-165",
    title: "The Smell Of Success",
    artist: "Local",
    duration: 170,
    file: "/sounds/The_smell_of_success.mp3",
  },
  {
    id: "local-166",
    title: "This Beauty",
    artist: "Local",
    duration: 129,
    file: "/sounds/This_Beauty.mp3",
  },
  {
    id: "local-167",
    title: "This Is Business",
    artist: "Local",
    duration: 192,
    file: "/sounds/This_Is_Business.wav",
  },
  {
    id: "local-168",
    title: "This Is Explainer Video Music",
    artist: "Local",
    duration: 152,
    file: "/sounds/This_Is_Explainer_Video_Music.mp3",
  },
  {
    id: "local-169",
    title: "This Is Love",
    artist: "Local",
    duration: 133,
    file: "/sounds/This_Is_Love.wav",
  },
  {
    id: "local-170",
    title: "This Travel",
    artist: "Local",
    duration: 135,
    file: "/sounds/This_Travel.mp3",
  },
  {
    id: "local-171",
    title: "This Is Beauty",
    artist: "Local",
    duration: 128,
    file: "/sounds/This_is_Beauty.mp3",
  },
  {
    id: "local-172",
    title: "This Is Business",
    artist: "Local",
    duration: 130,
    file: "/sounds/This_is_Business.mp3",
  },
  {
    id: "local-173",
    title: "This Is Summer",
    artist: "Local",
    duration: 148,
    file: "/sounds/This_is_Summer.mp3",
  },
  {
    id: "local-174",
    title: "This Is Tech",
    artist: "Local",
    duration: 158,
    file: "/sounds/This_is_Tech.mp3",
  },
  {
    id: "local-175",
    title: "Tokyo Coffee",
    artist: "Local",
    duration: 167,
    file: "/sounds/Tokyo_Coffee.wav",
  },
  {
    id: "local-176",
    title: "Travel",
    artist: "Local",
    duration: 136,
    file: "/sounds/Travel.mp3",
  },
  {
    id: "local-177",
    title: "Travel Vlog Folk",
    artist: "Local",
    duration: 111,
    file: "/sounds/Travel_Vlog_Folk.mp3",
  },
  {
    id: "local-178",
    title: "Trend Deep",
    artist: "Local",
    duration: 138,
    file: "/sounds/Trend_Deep.mp3",
  },
  {
    id: "local-179",
    title: "Trip",
    artist: "Local",
    duration: 133,
    file: "/sounds/Trip.mp3",
  },
  {
    id: "local-180",
    title: "Upbeat",
    artist: "Local",
    duration: 151,
    file: "/sounds/Upbeat.mp3",
  },
  {
    id: "local-181",
    title: "Upbeat Beauty Smooth Lounge Soul Rb",
    artist: "Local",
    duration: 149,
    file: "/sounds/Upbeat_Beauty_Smooth_Lounge_Soul_RB.mp3",
  },
  {
    id: "local-182",
    title: "Upbeat Folk",
    artist: "Local",
    duration: 128,
    file: "/sounds/Upbeat_Folk.mp3",
  },
  {
    id: "local-183",
    title: "Upbeat Pop",
    artist: "Local",
    duration: 134,
    file: "/sounds/Upbeat_Pop.mp3",
  },
  {
    id: "local-184",
    title: "Upbeat Presentation",
    artist: "Local",
    duration: 140,
    file: "/sounds/Upbeat_Presentation.mp3",
  },
  {
    id: "local-185",
    title: "Uplifting Acoustic Summer",
    artist: "Local",
    duration: 172,
    file: "/sounds/Uplifting_Acoustic_Summer.mp3",
  },
  {
    id: "local-186",
    title: "Uplifting Background Music Full Version",
    artist: "Local",
    duration: 159,
    file: "/sounds/Uplifting_Background_Music_full_version.mp3",
  },
  {
    id: "local-187",
    title: "Uplifting Indie Electronic",
    artist: "Local",
    duration: 190,
    file: "/sounds/Uplifting_Indie_Electronic.mp3",
  },
  {
    id: "local-188",
    title: "Uplifting Inspiration",
    artist: "Local",
    duration: 166,
    file: "/sounds/Uplifting_Inspiration.mp3",
  },
  {
    id: "local-189",
    title: "Uplifting Upbeat Corporate Motivational Full Version",
    artist: "Local",
    duration: 189,
    file: "/sounds/Uplifting_Upbeat_Corporate_Motivational_full_version.mp3",
  },
  {
    id: "local-190",
    title: "Warm Sleep",
    artist: "Local",
    duration: 127,
    file: "/sounds/Warm_Sleep.mp3",
  },
  {
    id: "local-191",
    title: "We Rhoose A Bright Future",
    artist: "Local",
    duration: 259,
    file: "/sounds/We_rhoose_a_Bright_Future.mp3",
  },
  {
    id: "local-192",
    title: "Wellness",
    artist: "Local",
    duration: 132,
    file: "/sounds/Wellness.wav",
  },
  {
    id: "local-193",
    title: "Wildkittytunes Technology Mp3",
    artist: "Local",
    duration: 147,
    file: "/sounds/WildKittyTunes_Technology_mp3.mp3",
  },
  {
    id: "local-194",
    title: "Withrelax",
    artist: "Local",
    duration: 175,
    file: "/sounds/WithRelax.mp3",
  },
  {
    id: "local-195",
    title: "With Relax",
    artist: "Local",
    duration: 175,
    file: "/sounds/With_Relax.mp3",
  },
  {
    id: "local-196",
    title: "Yourhappyface",
    artist: "Local",
    duration: 157,
    file: "/sounds/YourHappyFace.mp3",
  },
  {
    id: "local-197",
    title: "Your Happy Face",
    artist: "Local",
    duration: 157,
    file: "/sounds/Your_Happy_Face.mp3",
  },
  {
    id: "local-198",
    title: "Fashion",
    artist: "Local",
    duration: 137,
    file: "/sounds/fashion.mp3",
  },
  {
    id: "local-199",
    title: "Fashion House",
    artist: "Local",
    duration: 132,
    file: "/sounds/fashion_house.mp3",
  },
  {
    id: "local-200",
    title: "Frosty Morning Main",
    artist: "Local",
    duration: 143,
    file: "/sounds/frosty_morning_main.mp3",
  },
  {
    id: "local-201",
    title: "Full",
    artist: "Local",
    duration: 115,
    file: "/sounds/full.mp3",
  },
  {
    id: "local-202",
    title: "Main Track",
    artist: "Local",
    duration: 157,
    file: "/sounds/main_track.mp3",
  }
];
